# Generated by Django 5.0.6 on 2024-06-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON HOLD', 'On hold'), ('IN PROCESS', 'In Process'), ('COMPLETED', 'Completed')], default='ON HOLD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
